#!/bin/bash
# Master Test Runner for AvocadoDB
# Runs comprehensive validation and generates a test report

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
REPORT_FILE="$ROOT_DIR/test-report-$(date +%Y%m%d-%H%M%S).md"

cd "$ROOT_DIR"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         AvocadoDB Comprehensive Test Suite                   ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Check if database exists
if [ ! -f ".avocado/db.sqlite" ]; then
    echo "❌ Error: No database found at .avocado/db.sqlite"
    echo ""
    echo "Please run:"
    echo "  ./target/release/avocado init"
    echo "  ./target/release/avocado ingest test-docs/ --recursive"
    echo ""
    exit 1
fi

# Check if binary exists
if [ ! -f "target/release/avocado" ]; then
    echo "Building AvocadoDB..."
    cargo build --release
    echo ""
fi

# Start report
cat > "$REPORT_FILE" << 'EOF'
# AvocadoDB Test Report

**Generated:** $(date)

## Executive Summary

This report validates AvocadoDB's core guarantees:
- **100% Determinism**: Same query → Same result, every time
- **Performance**: Sub-500ms compilation for 8K token budgets
- **Token Efficiency**: 90-95% budget utilization

---

EOF

# Add system info to report
{
    echo "## System Information"
    echo ""
    echo "- Date: $(date)"
    echo "- Platform: $(uname -s) $(uname -m)"
    echo "- Rust version: $(rustc --version)"
    echo ""
} >> "$REPORT_FILE"

# Add database stats to report
{
    echo "## Database Statistics"
    echo ""
    echo '```'
    ./target/release/avocado stats
    echo '```'
    echo ""
} >> "$REPORT_FILE"

echo "Running tests..."
echo ""

# Run determinism test
echo "═══════════════════════════════════════════════════════════════"
echo "  DETERMINISM VALIDATION TEST"
echo "═══════════════════════════════════════════════════════════════"
echo ""

if "$SCRIPT_DIR/test-determinism.sh" > /tmp/determinism-output.txt 2>&1; then
    DETERMINISM_RESULT="✅ PASS"
    DETERMINISM_STATUS=0
else
    DETERMINISM_RESULT="❌ FAIL"
    DETERMINISM_STATUS=1
fi

cat /tmp/determinism-output.txt

# Add to report
{
    echo "## Determinism Validation"
    echo ""
    echo "**Result:** $DETERMINISM_RESULT"
    echo ""
    echo '```'
    cat /tmp/determinism-output.txt
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Run performance benchmark
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  PERFORMANCE BENCHMARK"
echo "═══════════════════════════════════════════════════════════════"
echo ""

if "$SCRIPT_DIR/benchmark.sh" > /tmp/benchmark-output.txt 2>&1; then
    BENCHMARK_RESULT="✅ PASS"
    BENCHMARK_STATUS=0
else
    BENCHMARK_RESULT="⚠️  PARTIAL"
    BENCHMARK_STATUS=0  # Benchmarks are informational
fi

cat /tmp/benchmark-output.txt

# Add to report
{
    echo "## Performance Benchmark"
    echo ""
    echo "**Result:** $BENCHMARK_RESULT"
    echo ""
    echo '```'
    cat /tmp/benchmark-output.txt
    echo '```'
    echo ""
} >> "$REPORT_FILE"

# Add conclusions to report
{
    echo "## Conclusions"
    echo ""
    if [ $DETERMINISM_STATUS -eq 0 ]; then
        echo "✅ **Determinism Guarantee:** AvocadoDB produces 100% deterministic results across all test iterations."
        echo ""
    else
        echo "❌ **Determinism Guarantee:** FAILED - Non-deterministic behavior detected."
        echo ""
    fi

    echo "### Performance Summary"
    echo ""
    echo "See benchmark results above for detailed timing analysis across different query types and token budgets."
    echo ""

    echo "---"
    echo ""
    echo "*Report generated by AvocadoDB Test Suite*"
} >> "$REPORT_FILE"

# Final summary
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "  TEST SUMMARY"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Determinism Test:    $DETERMINISM_RESULT"
echo "Performance Benchmark: $BENCHMARK_RESULT"
echo ""
echo "Full report saved to: $REPORT_FILE"
echo ""

if [ $DETERMINISM_STATUS -eq 0 ]; then
    echo "✅ All critical tests passed!"
    exit 0
else
    echo "❌ Some tests failed. See report for details."
    exit 1
fi
